# -*- coding: utf-8 -*-
"""Task7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BfHG3R-L6wazpUm64dJDNah0q4-DbyY
"""

import json

student = {
    "id": 1,
    "name": "tushar",
    "age": 20,
    "course": "python"
}

print(student["name"])

student["age"] = 21
del student["course"]

for k, v in student.items():
    print(k, ":", v)

with open("student.json", "w") as f:
    json.dump(student, f, indent=4)

with open("student.json", "r") as f:
    data = json.load(f)

print("from json:", data)